spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college
    username: root
    password: Raja@3013
    driver-class-name: com.mysql.cj.jdbc.Driver

h2:
  console:
    enabled: true

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  
server:
    port: 8084
